### ISSUE TITLE
Error on help command

### ISSUE THREAD

**Issue by Silwing** [SlimeKnights/TinkersMechworks#56]
I get the following error when typing "help" in a server with Tinkers Mechworks for 1.7.10 installed. Version 0.2.8. Single player works fine, the error only occurres with a dedicated server.

[20:36:06] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[20:36:06] [Server thread/ERROR]: Couldn't process command: 'help'
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.ComparableTimSort.mergeHi(Unknown Source) ~[?:1.7.0_10]
    at java.util.ComparableTimSort.mergeAt(Unknown Source) ~[?:1.7.0_10]
    at java.util.ComparableTimSort.mergeForceCollapse(Unknown Source) ~[?:1.7.0_10]
    at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.7.0_10]
    at java.util.ComparableTimSort.sort(Unknown Source) ~[?:1.7.0_10]
    at java.util.Arrays.sort(Unknown Source) ~[?:1.7.0_10]
    at java.util.Collections.sort(Unknown Source) ~[?:1.7.0_10]
    at net.minecraft.command.CommandHelp.func_71534_d(SourceFile:84) ~[au.class:?]
    at net.minecraft.command.CommandHelp.func_71515_b(SourceFile:38) ~[au.class:?]
    at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:371) [lt.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer

**Comment by snacdaws** [comment]
just had this same issue on my server and apparently i had my ram allocation too high because as soon as i lowered it it went back to normal
