### ISSUE TITLE
player disconnect on signal bus place event

### ISSUE THREAD

**Issue by Peav84** [SlimeKnights/TinkersMechworks#85]
Ftb Infinity Evolved official mode pac Version 2.2.2
Windows 7 64 bit
Java 8 update 66 

[17:20:13] [Netty IO #14/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote ho
st
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_66]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_66]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_66]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_66]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_66]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDi
rectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870)
~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketCha
nnel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(Abstra
ctNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
a:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
ntLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEven
tLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[17:20:13] [Server thread/INFO]: Peav420 lost connection: TranslatableComponent{
key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: A
n existing connection was forcibly closed by the remote host], siblings=[], styl
e=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, ob
fuscated=null, clickEvent=null, hoverEvent=null}}
[17:20:13] [Server thread/INFO]: Peav420 left the game

**Comment by Peav84** [comment]
As well crashed my single player

**Comment by Glassmaker** [comment]
From my testing it looks like it's Waila interaction bug have returned, marking this as duplicate, and reopening #82 for re-investigation.
